[package]
name = "dekinai"
version = "1.2.0"
description = "Dekinai is a simple and minimalistic file uploading API.\nIt provides the bare minimum feature set for file hosting services, while also being fast and portable."
categories = ["filesystem", "network-programming", "web-programming::http-server"]
keywords = ["file", "upload", "host", "hoster", "hosting"]
authors = ["Johann Rekowski <johann.rekowski@gmail.com>"]
repository = "https://github.com/HitomiTenshi/dekinai.git"
license = "MIT"
edition = "2024"
rust-version = "1.89.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-multipart = "0.7"
actix-web = { version = "4", default-features = false, features = ["macros"] }
clap = { version = "4", features = ["cargo", "env", "wrap_help"] }
derive_more = { version = "2", features = ["display", "error"] }
futures-util = { version = "0.3", default-features = false }
num_cpus = "1"
pbkdf2 = { version = "0.12", features = ["simple"] }
rand = "0.8"
sqlx = { version = "0.8", features = ["runtime-tokio-native-tls", "sqlite"] }
tokio = { version = "1", features = ["fs"] }

[profile.release]
codegen-units = 1
lto = true
strip = true
