CREATE TABLE IF NOT EXISTS UPLOADS (
    FILE_STEM TINYTEXT NOT NULL,
    FILE_EXTENSION TINYTEXT NOT NULL,
    DELETION_PASSWORD TEXT NOT NULL,
    PRIMARY KEY (FILE_STEM, FILE_EXTENSION)
) WITHOUT ROWID;
